### PR TITLE
Cleanup dragonfly template

### PR DESCRIPTION
**Pull request by strangelittlemonkey**
Some general cleanup of the DragonFly template.

### CODE REVIEW

**Comment by strangelittlemonkey** [comment]
Fixes #82

**Comment by mcandre** [comment]
The PR looks okay, though I would want to separate the DragonflyBSD upgrade into a distinct pull request from this one. If you'd like to do that, and resolve the merge conflict, then I'd be happy to test this change.

**Comment by strangelittlemonkey** [comment]
Ok. I've taken the last commit off and moved it, albeit improved, to a separate PR. I think you'll like it. :)

**Comment by mcandre** [comment]
PR looks good, will test this when I have some time

**Comment by mcandre** [comment]
Will rebuild the base box eventually, to reduce the file size.

**Pull request merged**
